database:
  host: us-prod-upstream-api001-oriole-db.postgres.database.azure.com
  user_name: dhos-sms@us-prod-upstream-api001-oriole-db
  su_name: postgres@us-prod-upstream-api001-oriole-db
  name: dhos-sms

environment: PRODUCTION
imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config-prod during a release
imagetag: r1.14.0
allow_drop_data: false
host_env: azure

gateway_url: https://api-us-prod.sensynehealth.com
country_code: US
twilio_account_sid: ACf7bcb7dd8bb212dc204110d8052a33f6

ingress:
  hostName: api-prod.sensynehealth.local
