database:
  host: uk-prod006-hog-db.postgres.database.azure.com
  user_name: dhos-sms@uk-prod006-hog-db
  su_name: postgres@uk-prod006-hog-db
  name: dhos-sms

environment: PRODUCTION
imagePullPolicy: IfNotPresent
# This placeholder value gets overridden by devops-release-config-prod during a release
imagetag: r1.14.0
allow_drop_data: false
host_env: azure

gateway_url: https://api-uk-prod.sensynehealth.com
country_code: GB
twilio_account_sid: ACad1d6402c8223659f6a4f42e1b7be4f8

ingress:
  hostName: api-prod.sensynehealth.local
