GCP_DOCKER_AUTH_MASTER: &GCP_DOCKER_AUTH
  auth:
    username: _json_key
    password: ${GOOGLE_AUTH}
version: 2.1
orbs:
  azure-acr: circleci/azure-acr@0.1.4
  ms-teams: cloudradar-monitoring/ms-teams@0.0.1
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Create coverage report dir
          command: mkdir -p ${COVERAGE_REPORT_DIR}
      - run:
          name: Set up tox tests
          command: |
            poetry self update
            poetry config http-basic.sensynehealth ${GEMFURY_DOWNLOAD_KEY} ''
            pip install --upgrade tox
      - restore_cache:
          keys:
            - v2-poetry-deps-{{ checksum "poetry.lock" }}
            - v2-poetry-deps-
      - run:
          name: Run tox tests
          command: tox -e py39
      - save_cache:
          key: v2-poetry-deps-{{ checksum "poetry.lock" }}
          paths:
            - .tox
      - persist_to_workspace:
          root: coverage-reports
          paths:
            - coverage.xml
  integration-test:
    docker:
      - image: gcr.io/dhos-stack/circleci-build-image:latest
        <<: *GCP_DOCKER_AUTH
    environment:
      REPORT_PORTAL_PROJECT: platform
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Auth with ACR
          command: source /usr/local/bin/deployment-helpers-v1.sh; authenticateToACR
      - run:
          name: Run the integration test script
          command: .circleci/run_integration_tests.sh  
  deploy-dev:
    docker:
      - image: gcr.io/dhos-stack/circleci-build-image:latest
        <<: *GCP_DOCKER_AUTH
    environment:
      K8S_DEV_DEPLOYMENT_NAME: deployment/dhos-sms-api-dep
      ACR_REPO_BASE: dhos
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Add build information
          command: .circleci/record_build_info.sh
      - run:
          name: Build image
          command: docker build -t ${CIRCLE_PROJECT_REPONAME} . --build-arg GEMFURY_DOWNLOAD_KEY
      - azure-acr/build-and-push-image:
          checkout: false
          login-server-name: ${AZURE_LOGIN_SERVER_NAME}
          registry-name: ${AZURE_REGISTRY_NAME}
          repo: ${ACR_REPO_BASE}/dhos-sms-api
          tag: dev,cb-${CIRCLE_BUILD_NUM},$(git log --pretty=format:'%h' -n 1)
          extra-build-args: --build-arg GEMFURY_DOWNLOAD_KEY
      - run:
          name: Deploy to UK dev cluster in Azure
          command: .circleci/deploy_azure_dev.sh uk uk-dev-api-upstream
      - ms-teams/report:
          only_on_fail: true
          webhook_url: ${MSTEAMS_NOTIFY_WEBHOOK_URL}
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test:
          context: engineering-build
      - integration-test:
          context: engineering-build
      - deploy-dev:
          context: dhos-deploy
          requires:
            - test
            - integration-test
          filters:
            branches:
              only:
                - develop
