apiVersion: v1
kind: ConfigMap
metadata:
  name: dhos-sms-api-cm
  labels:
    app: dhos-sms-api
data:
  DATABASE_HOST: {{ .Values.database.host }}
  DATABASE_USER: {{ .Values.database.user_name }}
  DATABASE_NAME: {{ .Values.database.name }}
  DATABASE_PORT: "5432"
  DATABASE_SU_USER: {{ .Values.database.su_name }}
  ALLOW_DROP_DATA: "{{.Values.allow_drop_data}}"
  ENVIRONMENT: {{ .Values.environment }}
  LOG_LEVEL: {{ .Values.log_level | default "INFO" }}
  TWILIO_CALL_BACK_URL: {{ .Values.gateway_url }}/dhos-sms/dhos/v1/sms/callback
  TWILIO_ACCOUNT_SID: {{ .Values.twilio_account_sid }}
  COUNTRY_CODE: {{ .Values.country_code }}
