apiVersion: v1
kind: Secret
metadata:
  name: dhos-sms-api-secrets
  labels:
    app: dhos-sms-api
data:
  DATABASE_PASSWORD: {{ .Values.database.user_password | b64enc }}
  DATABASE_SU_PASSWORD: {{ .Values.database.su_password | b64enc }}
  TWILIO_AUTH_TOKEN: {{ .Values.twilio_auth_token | b64enc }}
